### ISSUE TITLE
Create database facade

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2.0#30]
Create a database facade (probably in a `database/` directory) that exposes core database actions that commands/events can interact with. For now, focus on user-related actions; these can just be stubbed out, since the point of this ticket is more to get the database facade's API up and going so other modules can start calling it.

This doesn't necessarily have to be a whole class; it might be better to leave it as a set of functions (but I leave that up to the developers!).

**Comment by cheukyin699** [comment]
We assume that `DBFacade` only handles DynamoDB at the start, and if other things are needed, then we will adjust.
