### ISSUE TITLE
Start DynamoDb connection class

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2.0#33]
Create a class to encapsulate a connection to [DynamoDb](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html), using the [`boto3`](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) library. This will eventually be called from the database facade created in #30. For now it's probably enough to stub out some of the major methods, and possibly start methods to convert instances of our data model into DynamoDb equivalents.

**Comment by rwblickhan** [comment]
Actually creating the connection to DynamoDb may have to wait for #24, since we don't currently have a DynamoDb table set up.

**Comment by cheukyin699** [comment]
- document user table
- write tests that require local session of dynamodb (temporary)
- make the tests run automatically (fun fun times)
- `delete_user` function that deletes a user given a `slack_id`
