### ISSUE TITLE
Handle default command parsing for command classes

### ISSUE THREAD

**Issue by jacqueschen1** [ubclaunchpad/rocket2.0#63]
Currently, if a command such as `@rocket user` is handled without any subparsers, an error is returned. Add a default handler so that handler returns help text.

**Comment by cheukyin699** [comment]
Apparently, this is a larger issue than I realized. The `argparse` library likes to exit unceremoniously after you don't play nice with it (give it invalid/non-existent arguments). This is why everything is failing and dying.

Will be having another go at it later.
