### ISSUE TITLE
Auto-deploy python documentation

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2.0#93]
Would be nice if we had documentation automatically deployed onto Read the Docs. More specifically, the API docs on database, commands, and maybe a short little tutorial on how everything works together, and how to build a plugin.

Might need some way to access through ubclaunchpad (since this repo is under the organization).

**Comment by rwblickhan** [comment]
Oh, one other thing I just thought of - there should be a Read the Docs badge (maybe check [shields.io](https://shields.io/#/) if you can't find it?) and we should add that to the README.
